---
title: Extracting Parking Lot Structures from Aerial Photographs
subtitle:
author: "[Nisim Hurst](mailto:langheran@gmail.com)"
date: Thursday 2 May 2019
abstract: ""
bibliography: Extracting-Parking-Lot-Structures-from-Aerial-Photographs/Extracting-Parking-Lot-Structures-from-Aerial-Photographs.bib
urlcolor: blue
biblio-style: "authoryear" # "apalike" "apa" "authoryear"
link-citations: true
csl: ieee.csl
output:
  bookdown::pdf_document2:
    pandoc_args:
      - "--csl"
      - "ieee.csl"
      - "--metadata"
      - "link-citations"
      - "--filter"
      - "pandoc-eqnos"
    toc: no
    toc_depth: 5
    number_sections: no
    keep_tex: true
    citation_package: biblatex
#    includes:
#      before_body: ../doc-prefix.tex
header-includes: |
    \usepackage{float}
    \usepackage{graphicx}
    \usepackage{subfig}
    \usepackage{fancyhdr}
    \pagestyle{fancy}
    \usepackage{truncate}
    \renewcommand{\subsectionmark}[1]{\markright{#1}{}}
    \fancyhf{}
    \lhead{\small\truncate{400pt}{\rightmark}}
    \rhead{\small\hyperref[toc]{Table Of Contents}}
    \rfoot{Page \thepage}
    \usepackage{caption}
    \usepackage{listings}
    \usepackage{attachfile}
    \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
    \usepackage{cleveref}

    \usepackage{xcolor}
    \definecolor{block-gray}{gray}{0.85}
    \usepackage{environ}
    \NewEnviron{quoteblock}
    {\colorbox{block-gray}{
    \parbox{\dimexpr\linewidth-2\fboxsep\relax}{
    \small\addtolength{\leftskip}{10mm}
    \addtolength{\rightskip}{10mm}
    \BODY}}
    }
    \renewcommand{\quote}{\quoteblock}
    \renewcommand{\endquote}{\endquoteblock}
    \ifdef{\printbibliography}{
       \defbibheading{subsubbibliography}[\refname]{\subsubsection*{#1}}
       \let\oldprintbibliography\printbibliography
       \renewcommand{\printbibliography}[1]{
          \phantomsection
          \addcontentsline{toc}{section}{References}
          \oldprintbibliography[title={References},heading=subsubbibliography]
          }
    }{

    }
#site: bookdown::bookdown_site
#documentclass: extarticle
#geometry: "left=1cm, right=1cm, top=2.5cm, bottom=2.5cm"
#fontsize: 17pt
#linestretch: 1.5
---
\label{toc}

## Extracting Parking Lot Structures from Aerial Photographs

The article was written by [@Cheng_2014]. It was was cited [1](https://scholar.google.com/scholar?cites=13052058500546908032&as_sdt=2005&sciodt=0,5&hl=en) times according to Google Scholar. The task performed was individual parking spot detection using correctness and completeness metrics. A second task was determining the parking lot structure in the form of global parameters, i.e. width, length and angle.

### Hypothesis

Applying the Hough transform twice after having determined the principle orientations and using this result to estimate global parameters for the size and angle of the parking spots will achieve better than just using the Hough transform.

### Evidence and Results

#### Dataset

An aerial image covering 1,500m x 850m with a resolution 5cm per pixel was used. This image includes 3 parking lots with different orientations, occupation density and quality. Parking lot A has 36 parking spots, B 51 spots and C 54; accruing to a total of 141 parking spots.

#### Results

The results are presented in correctness and completeness. Correctness is the ratio between the correctly extracted parking spaces and the total extracted parking spaces. Completeness is the ratio between correctly extracted parking spaces and the total real parking spaces. A custom individual correctness indicator function that evaluates a set of rules is used, shown in Equation @eq:eq1.

$$
\begin{cases}
L_1-L_2<0.2*L_2\\
W_1-W_2<0.2*W_2\\
D<\sqrt{(0.2*L_2)^2+(0.2*W_2)^2}\\
\alpha<3
\end{cases}
$$ {#eq:eq1}
$$\\$$

Error of the global parameters, i.e. length, width and angle is shown as the absolute difference between the real number and the estimated number.

Error of the geometrical estimation is calculated by comparing each of the four vectors formed by the four corners of the parking spot to the manually annotated vectors. Mean error, root mean square error and maximum error are used for this comparison.

### Contribution

First, the paper provides a method using several optional techniques. Principal orientation calculation is proposed by using Hough transform twice. Also, a self-adaptive growth technique merges the lines. It presents comparative results for this element alone. 

A second contribution is the resiliency showed over 3 distinct parking lots. 

### Weaknesses

The metric was defined by the authors without giving any intuition neither on the literature nor stemming from the nature of the problem. Furthermore, the threshold in this metric are assumed and no experimentation was done for calculating it.

Also, the canonical width,  length and angle are calculated globally on a per-parking basis.

### Future Work

The authors propose using the parked vehicles to parking lot extraction. Also, it would be desirable a further algorithm that can detect an accurate parking lot area without human intervention because the method is based on this assumption. 