---
title: Chinese Whispers - An Efficient Graph Clustering Algorithm
subtitle:
author: "[Nisim Hurst](mailto:langheran@gmail.com)"
date: Tuesday 14 May 2019
abstract: ""
bibliography: Chinese-Whispers---An-Efficient-Graph-Clustering-Algorithm/Chinese-Whispers---An-Efficient-Graph-Clustering-Algorithm.bib
urlcolor: blue
biblio-style: "authoryear" # "apalike" "apa" "authoryear"
link-citations: true
csl: ieee.csl
output:
  bookdown::pdf_document2:
    pandoc_args:
      - "--csl"
      - "ieee.csl"
      - "--metadata"
      - "link-citations"
      - "--filter"
      - "pandoc-eqnos"
    toc: no
    toc_depth: 5
    number_sections: no
    keep_tex: true
    citation_package: biblatex
#    includes:
#      before_body: ../doc-prefix.tex
header-includes: |
    \usepackage{float}
    \usepackage{graphicx}
    \usepackage{subfig}
    \usepackage{fancyhdr}
    \pagestyle{fancy}
    \usepackage{truncate}
    \renewcommand{\subsectionmark}[1]{\markright{#1}{}}
    \fancyhf{}
    \lhead{\small\truncate{400pt}{\rightmark}}
    \rhead{\small\hyperref[toc]{Table Of Contents}}
    \rfoot{Page \thepage}
    \usepackage{caption}
    \usepackage{listings}
    \usepackage{attachfile}
    \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
    \usepackage{cleveref}

    \usepackage{xcolor}
    \definecolor{block-gray}{gray}{0.85}
    \usepackage{environ}
    \NewEnviron{quoteblock}
    {\colorbox{block-gray}{
    \parbox{\dimexpr\linewidth-2\fboxsep\relax}{
    \small\addtolength{\leftskip}{10mm}
    \addtolength{\rightskip}{10mm}
    \BODY}}
    }
    \renewcommand{\quote}{\quoteblock}
    \renewcommand{\endquote}{\endquoteblock}
    \ifdef{\printbibliography}{
       \defbibheading{subsubbibliography}[\refname]{\subsubsection*{#1}}
       \let\oldprintbibliography\printbibliography
       \renewcommand{\printbibliography}[1]{
          \phantomsection
          \addcontentsline{toc}{section}{References}
          \oldprintbibliography[title={References},heading=subsubbibliography]
          }
    }{

    }
    \input{algorithm.tex}
site: bookdown::bookdown_site
documentclass: extarticle
geometry: "left=1cm, right=1cm, top=2.5cm, bottom=2.5cm"
fontsize: 17pt
linestretch: 1.5
---
\label{toc}

## Chinese Whispers - An Efficient Graph Clustering Algorithm
The article was written by [@biemann2006]. It was was cited [303](https://scholar.google.com/scholar?cites=11936713141221423099&as_sdt=2005&sciodt=0,5&hl=en) times according to Google Scholar. The task performed was graph-clustering. They used x metric over x.

### Hypothesis

A randomized graph-clustering algorithm would perform well of small worlds.

### Evidence and Results

#### Dataset

The dataset used are all from the natural language processing world. 

#### Results

### Contribution

The authors propose 

\begin{algorithm}[H]
	\caption{Chinese Whispers clustering subject to pairwise constraints}\label{al1}
	\begin{algorithmic}[1]
		\INPUT{An initial graph $G$ of $V$ multidimensional vectors to be clustered, the must-link pairs symmetric relations  $ ML=\{ (V_i, V_j)| i\neq j \cap C(V_i) = C(V_j)\}$ and $ CL=\{ (V_i, V_j)| i\neq j \cap C(V_i) \neq C(V_j)\}$}
		\OUTPUT{An assignment of the clusters for each vertex $\in$ $ G.V $}
		\Procedure{ConstrainedCW}{$G$,$ML$,$CL$}
			\State MustLink $\gets$ Connected-Components($G.V$, $ML$)
      \State CannotLink $\gets$ Connected-Components($G.V$, $CL$)
      \State CWWrapper(\&$G$,$MustLink$,$CannotLink$)
      \State\Return ClusterAssignments
		\EndProcedure
	\end{algorithmic}
\end{algorithm}

Small world graphs 

### Controversial Ideas

### Weaknesses

### Future Work