---
title: Clustering Millions of Faces By Identity
subtitle:
author: "[Nisim Hurst](mailto:langheran@gmail.com)"
date: Tuesday 14 May 2019
abstract: ""
bibliography: Clustering-Millions-of-Faces-By-Identity/Clustering-Millions-of-Faces-By-Identity.bib
urlcolor: blue
biblio-style: "authoryear" # "apalike" "apa" "authoryear"
link-citations: true
csl: ieee.csl
output:
  bookdown::pdf_document2:
    pandoc_args:
      - "--csl"
      - "ieee.csl"
      - "--metadata"
      - "link-citations"
      - "--filter"
      - "pandoc-eqnos"
    toc: no
    toc_depth: 5
    number_sections: no
    keep_tex: true
    citation_package: biblatex
#    includes:
#      before_body: ../doc-prefix.tex
header-includes: |
    \usepackage{float}
    \usepackage{graphicx}
    \usepackage{subfig}
    \usepackage{fancyhdr}
    \pagestyle{fancy}
    \usepackage{truncate}
    \renewcommand{\subsectionmark}[1]{\markright{#1}{}}
    \fancyhf{}
    \lhead{\small\truncate{400pt}{\rightmark}}
    \rhead{\small\hyperref[toc]{Table Of Contents}}
    \rfoot{Page \thepage}
    \usepackage{caption}
    \usepackage{listings}
    \usepackage{attachfile}
    \makeatletter\renewcommand*{\fps@figure}{H}\makeatother
    \usepackage{cleveref}

    \usepackage{xcolor}
    \definecolor{block-gray}{gray}{0.85}
    \usepackage{environ}
    \NewEnviron{quoteblock}
    {\colorbox{block-gray}{
    \parbox{\dimexpr\linewidth-2\fboxsep\relax}{
    \small\addtolength{\leftskip}{10mm}
    \addtolength{\rightskip}{10mm}
    \BODY}}
    }
    \renewcommand{\quote}{\quoteblock}
    \renewcommand{\endquote}{\endquoteblock}
    \ifdef{\printbibliography}{
       \defbibheading{subsubbibliography}[\refname]{\subsubsection*{#1}}
       \let\oldprintbibliography\printbibliography
       \renewcommand{\printbibliography}[1]{
          \phantomsection
          \addcontentsline{toc}{section}{References}
          \oldprintbibliography[title={References},heading=subsubbibliography]
          }
    }{

    }
site: bookdown::bookdown_site
documentclass: extarticle
geometry: "left=1cm, right=1cm, top=2.5cm, bottom=2.5cm"
fontsize: 17pt
linestretch: 1.5
---
\label{toc}

## Clustering Millions of Faces by Identity

The article was written by [@otto2018]. It was was cited [44](https://scholar.google.com/scholar?cites=9743611198042490448&as_sdt=2005&sciodt=0,5&hl=en) times according to Google Scholar. The task performed was face clustering. They used the Pairwise F-measure metric over clusters with distractor images. They also developed their own metric for measuring internal cluster quality using just the k-top nearest neighbors.

### Hypothesis
Deep features clustered using only the top-k nearest neighbors in an approximate rank-order clustering will produce a more scalable and a more accurate face clustering algorithm. This algorithm will be able to overcome the presence of millions distractor images and class imbalance.

The network architecture to produce a 320D feature vector was VGG16 proposed by [@Simonyan2014]. The rank-order clustering algorithm is based on [@zhu2011]. Their k-d tree implementation for calculating just the 200-top nearest neighbors is based on [@muja2014]. 

### Evidence and Results
Evidence is presented first over a small dataset and the over an augmented version of the datasets with millions of distractor images.

#### Dataset
The feature extractor was trained with the CASIA-webface. LFW, YTF were used for cluster evaluation, the former over static images and the latter over videos. Webfaces was used to augment the  LFW. Here is a brief description of each:

\small
|        |                            # Instances                            | Resolution |          Scenery          |     Author     |
| ------ | ----------------- | ---------- | ------------- | -------------- |
| LFW    | 13233 images of 5749. Only 1680 subjects have two or more photos. | ??, variable head angle |                         Color, different Poses and Backgrounds.| [@huang2008]   |
| YTF    | 3425 videos of 1595 subjects.                                     |      100x100, variable enclosing area      |            Color, different Poses and Backgrounds.                  | [@wolf2011]    |
| Webfaces |     123,654,141 distractor images.                                   |     N/A       | N/A | [@otto2018] |
| CASIA-webface     | 494,414 images of 10,575 subjects.                                             | 120x165    | Color, different Poses and Backgrounds.           | [@yi2014]    |
: \label{tab:table1} Main characteristics of the four datasets that were used to test the improved CW.

\normalsize

#### Results

First, the authors present Pairwise F-measure evaluated in the LFW dataset without any distractor images. The algorithm obtained the highest F-Measure and lowest run-time. The algorithm is proficient at handling class unbalance. 

Second, the authors show performance on the augmented LFW dataset and the decay rate of each algorithm under these conditions. The proposed algorithm shows the highest resiliency compared to the decays ensued in the other algorithm. 

Having benchmarked the algorithm in contrast to the other methods, the authors estimate internal performance under increasing levels of distractor images and search spaces. This scalability test was then repeated while increasing both the number of distractor images and the number of cores. Each core enabled the code to run in distributed chunks over separate machines. Deduplication on the full 123M dataset resulted in a 121M dataset which achieved 0.32 F-Measure, in contrast with the previously achieved 0.27 F-Measure.

Also, given that having a high number of similar frames on each video can affect grouping identities between videos, the authors present the results of the algorithm using a sample of 3 frames per video in contrast to the results obtained over all the frames. 

Finally, in an attempt to measure the effectiveness of the proposed internal measures, the authors presents their correlation to the pairwise precision external measure. As an alternative to correlation, the authors propose to compare average precision of the top-100 clusters ranked by the internal measure.

### Contribution

Firstly, the authors improved the Rank-Order clustering algorithm proposed by [@zhu2011]. The original Rank-Order has the disadvantage that it requires $O(n^2)$. The authors propose to use the FLANN library implementation of the randomized k-d tree algorithm to compute the list of top-k nearest neighbors [@hartley2008]. Just one iteration is used. This approximate version had better performance compared to the exact rank-order and was faster than all the methods tested.

Secondly, the authors improved the internal quality metric of Modularization quality (MQ) [@mancoridis1998] by just counting shared neighbors in the top-k nearest neighbors list. Even though cluster's external quality was obviated, the authors propose a ranking evaluation protocol inspired in the field of retrieval analysis.

Thirdly, the authors provide an augmented dataset as a matter of baseline to assess the accuracy of the algorithm under the effect of distractor images that are out of the face clusters.  

### Weaknesses
The method using the dataset with the full 123M distractor images produces a representation that needs to be distributed in chunks across servers, each one process about a million image instances. However, the authors don't provide an efficient algorithm for merging the results nor prove that the algorithm is unaffected in single-thread environments.

Also, the method is dependent of a $k$ that depends on the number of instances, but the authors don't specify how $k$  should be modified. They tested with different  

### Future Work

Otto et al. mentions that the dimensional vector representation could be improved through a better deep model architect that perform better on profile/side faces. 

It would be beneficial to enforce pairwise constraints like must-link and cannot-link. Also the authors 